# Generated by Django 5.2 on 2025-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agenttask_agenttaskstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
