# Generated by Django 5.2 on 2025-05-07 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_agent_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='BrowserUseAgent',
        ),
        migrations.RenameModel(
            old_name='AgentTask',
            new_name='BrowserUseAgentTask',
        ),
        migrations.RenameModel(
            old_name='AgentTaskStep',
            new_name='BrowserUseAgentTaskStep',
        ),
        migrations.RemoveConstraint(
            model_name='browseruseagent',
            name='unique_agent_user_name',
        ),
        migrations.RemoveConstraint(
            model_name='browseruseagenttaskstep',
            name='unique_agent_task_step_task_step_number',
        ),
        migrations.AddConstraint(
            model_name='browseruseagent',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_browser_use_agent_user_name'),
        ),
        migrations.AddConstraint(
            model_name='browseruseagenttaskstep',
            constraint=models.UniqueConstraint(fields=('task', 'step_number'), name='unique_browser_use_agent_task_step_task_step_number'),
        ),
    ]
