# Generated by Django 5.2 on 2025-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_browseruseagenttask_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browseruseagenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
