# Generated by Django 5.2 on 2025-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_browseruseagenttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagenttask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='browseruseagenttask',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
