# Generated by Django 5.2 on 2025-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_browseruseagenttask_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='raw_key',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
