# Generated by Django 5.2 on 2025-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_raw_key_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagenttask',
            name='output_schema',
            field=models.JSONField(blank=True, help_text='Optional JSON schema to define structured output from the agent', null=True),
        ),
    ]
