# Generated by Django 5.2 on 2025-05-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_input_data_to_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browseruseagenttask',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.browseruseagent'),
        ),
    ]
