# Generated by Django 5.2 on 2025-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_browseruseagenttask_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagenttask',
            name='encrypted_secrets',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='browseruseagenttask',
            name='secret_keys',
            field=models.JSONField(blank=True, help_text='List of secret keys that were provided (for audit purposes)', null=True),
        ),
    ]
