# Generated by Django 5.2 on 2025-06-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cleanup_django_celery_beat_tables'),
        ('api', '0021_task_credit_system'),
        ('api', '0022_backfill_taskcredit'),
    ]

    operations = [
    ]
