# Generated by Django 5.2 on 2025-06-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20250615_1737'),
    ]

    # Remove unique constraint on TaskCredit model - this is to allow us to have multiple null invoice IDs per user,
    # for things like one-off grants
    operations = [
        migrations.RemoveConstraint(
            model_name='taskcredit',
            name='unique_task_credit_invoice',
        ),
    ]
