# Generated by Django 5.2 on 2025-06-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_decodo_models'),
        ('api', '0024_remove_taskcredit_unique_task_credit_invoice'),
    ]

    operations = [
    ]
