# Generated by Django 5.2 on 2025-06-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20250616_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='task_quota',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='tasks_used',
        ),
        migrations.AddField(
            model_name='taskcredit',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('startup', 'Startup')], default='free', help_text='The plan under which these credits were granted', max_length=32),
        ),
    ]
