# Generated by Django 5.2 on 2025-06-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_userquota_task_quota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[('free', 'Free'), ('startup', 'Startup')], default='free', help_text="The user's subscription plan", max_length=32)),
                ('max_extra_tasks', models.PositiveIntegerField(default=0, help_text='Maximum number of additional tasks allowed beyond plan limits')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Billing',
                'verbose_name_plural': 'User Billing',
            },
        ),
    ]
