# Generated by Django 5.2 on 2025-06-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_proxyserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyserver',
            name='decodo_ip',
            field=models.OneToOneField(blank=True, help_text='Associated Decodo IP record (if this proxy is from Decodo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_server', to='api.decodoip'),
        ),
    ]
