# Generated by Django 5.2 on 2025-06-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_proxyserver_decodo_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='decodoip',
            name='port',
            field=models.PositiveIntegerField(default=0, help_text='Port number used to discover this IP'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='decodoip',
            index=models.Index(fields=['port'], name='api_decodoi_port_4bb967_idx'),
        ),
    ]
