# Generated by Django 5.2 on 2025-06-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userbilling_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbilling',
            name='max_extra_tasks',
            field=models.IntegerField(default=0, help_text='Maximum number of additional tasks allowed beyond plan limits. 0 means no extra tasks, -1 means unlimited.'),
        ),
    ]
