# Generated by Django 5.2 on 2025-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_userbilling_max_extra_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcredit',
            name='additional_task',
            field=models.BooleanField(default=False, help_text='Whether this credit was granted as an additional task beyond the plan limits'),
        ),
    ]
