# Generated by Django 5.2 on 2025-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20250618_2101'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='decodoip',
            constraint=models.UniqueConstraint(fields=('ip_block', 'port'), name='unique_decodo_ip_block_port'),
        ),
    ]
