# Generated by Django 5.2 on 2025-06-18 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20250618_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagent',
            name='preferred_proxy',
            field=models.ForeignKey(blank=True, help_text='Preferred proxy server for this browser agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browser_agents', to='api.proxyserver'),
        ),
    ]
