# Generated by Django 5.2 on 2025-06-18 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_browseruseagent_preferred_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='browseruseagent',
            index=models.Index(fields=['preferred_proxy'], name='api_browser_preferr_4ec822_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyserver',
            index=models.Index(fields=['is_active', 'static_ip'], name='proxy_active_static_ip_idx'),
        ),
    ]
