# Generated by Django 5.2 on 2025-06-18 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_browseruseagent_api_browser_preferr_4ec822_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyHealthCheckSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this health check', max_length=128)),
                ('prompt', models.TextField(help_text='Prompt that describes what the health check should do')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this health check spec is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='api_proxyhe_is_acti_198c6f_idx'), models.Index(fields=['name'], name='api_proxyhe_name_f8455b_idx')],
            },
        ),
    ]
