# Generated by Django 5.2 on 2025-06-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_taskcredit_additional_task'),
        ('api', '0037_allow_null_user_for_health_checks'),
    ]

    operations = [
    ]
