# Generated by Django 5.2 on 2025-06-22 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_persistent_agent_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagent',
            name='schedule',
            field=models.CharField(blank=True, help_text='Cron-like schedule expression', max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Schedule must be a valid cron expression or shorthand like @daily', regex='^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\\d+(ns|us|µs|ms|s|m|h))+)|([*\\d\\-,/# ]+)$')]),
        ),
    ]
