# Generated by Django 5.2 on 2025-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_persistentagent_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this agent is currently active'),
        ),
    ]
