# Generated by Django 5.2 on 2025-06-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_persistentagentstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentCronTrigger',
            fields=[
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cron_trigger', serialize=False, to='api.persistentagentstep')),
                ('cron_expression', models.CharField(help_text='Cron expression that scheduled this execution (captured at trigger time)', max_length=128)),
            ],
            options={
                'ordering': ['-step__created_at'],
                'indexes': [models.Index(fields=['cron_expression'], name='pa_cron_expr_idx')],
            },
        ),
    ]
