# Generated by Django 5.2 on 2025-06-27 16:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_persistentagentcommssnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagentmessage',
            name='seq',
            field=models.CharField(db_index=True, default=api.models.generate_ulid, editable=False, max_length=26, unique=True),
        ),
    ]
