# Generated by Django 5.2 on 2025-06-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_persistentagentmessage_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentSystemStep',
            fields=[
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='system_step', serialize=False, to='api.persistentagentstep')),
                ('code', models.CharField(choices=[('PROCESS_EVENTS', 'Process Events'), ('SNAPSHOT', 'Snapshot')], max_length=64)),
                ('notes', models.TextField(blank=True, help_text='Optional free-form notes for debugging / context')),
            ],
            options={
                'ordering': ['-step__created_at'],
                'indexes': [models.Index(fields=['code'], name='pa_sys_code_idx')],
            },
        ),
    ]
