# Generated by Django 5.2 on 2025-06-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_persistentagentsystemstep'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='persistentagentstep',
            index=models.Index(fields=['agent', 'created_at'], name='pa_step_agent_ts_idx'),
        ),
    ]
