# Generated by Django 5.2 on 2025-06-30 19:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_cleanup_orphaned_browser_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='execution_environment',
            field=models.CharField(default=api.models.get_default_execution_environment, help_text="The execution environment this agent was created in (e.g., 'local', 'staging', 'prod')", max_length=64),
        ),
    ]
