# Generated by Django 5.2 on 2025-07-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_persistentagent_execution_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='preferred_contact_endpoint',
            field=models.ForeignKey(blank=True, help_text='Communication endpoint (email/SMS/etc.) the agent should use by default to reach its owner user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_agents', to='api.persistentagentcommsendpoint'),
        ),
    ]
