# Generated by Django 5.2 on 2025-07-22 01:10

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_persistentagent_preferred_contact_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcredit',
            name='available_credits',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('credits'), '-', models.F('credits_used')), output_field=models.IntegerField()),
        ),
    ]
