# Generated by Django 5.2 on 2025-07-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_usagethresholdsent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usagethresholdsent',
            table=None,
        ),
    ]
