# Generated by Django 5.2 on 2025-07-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_usagethresholdsent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='encrypted_secrets',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='secret_keys',
            field=models.JSONField(blank=True, help_text='List of secret keys that were provided (for audit purposes)', null=True),
        ),
    ]
