# Generated by Django 5.2 on 2025-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_convert_secrets_to_domain_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browseruseagenttask',
            name='secret_keys',
            field=models.JSONField(blank=True, help_text="Dictionary mapping domain patterns to secret keys (for audit purposes). Format: {'https://example.com': ['key1', 'key2']}", null=True),
        ),
        migrations.AlterField(
            model_name='persistentagent',
            name='secret_keys',
            field=models.JSONField(blank=True, help_text="Dictionary mapping domain patterns to secret keys (for audit purposes). Format: {'https://example.com': ['key1', 'key2']}", null=True),
        ),
    ]
