# Generated by Django 5.2 on 2025-07-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_browseruseagenttask_secret_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcredit',
            name='grant_type',
            field=models.CharField(choices=[('Plan', 'Plan'), ('Compensation', 'Compensation'), ('Promo', 'Promo')], default='Plan', help_text='Type of grant for these credits (e.g., PLAN, COMPENSATION, PROMO)', max_length=32),
        ),
        migrations.AddField(
            model_name='taskcredit',
            name='voided',
            field=models.BooleanField(default=False,
                                      help_text='Whether this credit block has been voided and should not be used'),
        ),
    ]
