# Generated by Django 5.2 on 2025-07-26 14:32

from django.db import migrations, models
from django.db.models.functions.datetime import TruncMonth


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_taskcredit_grant_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcredit',
            name='grant_month',
            field=models.GeneratedField(
                db_persist=True,
                expression=TruncMonth('granted_date'),
                output_field=models.DateField()
            ),
        ),
    ]
