# Generated by Django 5.2 on 2025-07-26 14:33

from django.db import migrations, models

from constants.grant_types import GrantTypeChoices


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_add_grant_month'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskcredit',
            constraint=models.UniqueConstraint(
                condition=models.Q(('additional_task', False), ('grant_type', 'Plan'), ('plan', 'free'),
                                   ('voided', False)),
                fields=('user', 'plan', 'grant_month'),
                name='uniq_free_plan_block_per_month'),
        ),
    ]
