# Generated by Django 5.2 on 2025-07-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_persistentagentsecret_and_migrate_secrets'),
    ]

    operations = [
    ]
