# Generated by Django 5.2 on 2025-07-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_persistentagentsecret_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagentsecret',
            name='name',
            field=models.CharField(help_text="Human-readable name for this secret (e.g., 'X Password', 'API Key')", max_length=128),
        ),
    ]
