# Generated by Django 5.2 on 2025-07-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_persistentagentsecret_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagentsecret',
            name='key',
            field=models.CharField(blank=True, help_text='Secret key name (auto-generated from name, alphanumeric with underscores only)', max_length=64),
        ),
    ]
