# Generated by Django 5.2 on 2025-07-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_persistentagentsecret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagentsecret',
            name='requested',
            field=models.BooleanField(default=False, help_text='Whether this secret has been requested but does not have a value yet'),
        ),
    ]
