# Generated by Django 5.2 on 2025-07-27 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_add_credentials_provided_system_step_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbilling',
            name='billing_cycle_anchor',
            field=models.IntegerField(default=1, help_text='Day of the month when billing cycle starts (1-31). 1 means start on the 1st of each month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
