# Generated by Django 5.2 on 2025-07-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_userphonenumber'),
        ('api', '0076_uniq_free_plan_blocorrect_addl_task_grant_and_expiration'),
    ]

    operations = [
    ]
