# Generated by Django 5.2 on 2025-07-29 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_merge_20250728_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=34, unique=True)),
                ('phone_number', models.CharField(help_text='The phone number in E.164 format (e.g., +1234567890)', max_length=15, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio')], default='twilio', help_text='Optional provider name for the SMS service (e.g., Twilio)', max_length=64)),
                ('is_sms_enabled', models.BooleanField(default=True)),
                ('is_mms_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this number is currently active and can be used for sending/receiving messages')),
                ('released_at', models.DateTimeField(blank=True, help_text='Timestamp when this number was released (if applicable)', null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
