# Generated by Django 5.2 on 2025-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_smsnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnumber',
            name='messaging_service_sid',
            field=models.CharField(blank=True, db_index=True, max_length=34, null=True),
        ),
    ]
