# Generated by Django 5.2 on 2025-07-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_smsnumber_messaging_service_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonenumber',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
