# Generated by Django 5.2 on 2025-08-01 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_link_shortener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshortener',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
