# Generated by Django 5.2 on 2025-08-01 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_alter_linkshortener_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='browseruseagenttask',
            index=models.Index(fields=['status', 'created_at'], name='task_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='browseruseagenttask',
            index=models.Index(fields=['created_at'], name='task_created_idx'),
        ),
    ]
