# Generated by Django 5.2 on 2025-08-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_agentfilespace_agentfilespaceaccess_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentfsnode',
            name='chk_dir_has_no_content',
        ),
    ]
