# Generated by Django 5.2 on 2025-08-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_agentfsnode_chk_dir_has_no_content'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentfsnode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('filespace', 'name'), name='unique_name_per_filespace_root'),
        ),
    ]
