# Generated by Django 5.2 on 2025-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_update_unique_constraints_exclude_deleted'),
    ]

    atomic = False

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS agentfsnode_parent_only_idx ON api_agentfsnode (parent_id);",
            reverse_sql="DROP INDEX IF EXISTS agentfsnode_parent_only_idx;",
        ),
    ]
