# Generated by Django 5.2 on 2025-08-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_unique_default_filespace_per_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshortener',
            name='url',
            field=models.URLField(help_text='Destination URL', max_length=2048),
        ),
    ]
