# Generated by Django 5.2 on 2025-08-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_linkshortener_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagentmessageattachment',
            name='filespace_node',
            field=models.ForeignKey(blank=True, help_text='If imported to a filespace, the created AgentFsNode this attachment maps to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_attachments', to='api.agentfsnode'),
        ),
    ]
