# Generated by Django 5.2 on 2025-08-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_organization_organizationinvite_and_more'),
        ('api', '0092_persistentagentmessageattachment_filespace_node'),
    ]

    operations = [
    ]
