# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_merge_20250819_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='organization',
            field=models.ForeignKey(
                to='api.organization',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='persistent_agents',
                help_text='Owning organization, if any. If null, owned by the creating user.'
            ),
        ),
    ]

