# Generated by Django 5.2 on 2025-08-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_add_waffle_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagentmessage',
            name='cc_endpoints',
            field=models.ManyToManyField(blank=True, help_text='CC recipients for email or additional recipients for group SMS', related_name='cc_messages', to='api.persistentagentcommsendpoint'),
        ),
    ]
