# Generated by Django 5.2 on 2025-08-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_persistentagent_enabled_mcp_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='mcp_tool_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary mapping MCP tool names to last usage timestamps for LRU tracking'),
        ),
    ]
