# Generated by Django 5.2 on 2025-08-27 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_add_contact_request_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commsallowlistrequest',
            name='allowlist_entry',
        ),
        migrations.AddField(
            model_name='commsallowlistrequest',
            name='allowlist_invitation',
            field=models.ForeignKey(blank=True, help_text='Invitation created when request was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_request', to='api.agentallowlistinvite'),
        ),
    ]
