# Generated by Django 5.2 on 2025-08-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_add_mcp_tool_usage'),
        ('api', '0102_update_contact_request_invitation_field'),
    ]

    operations = [
    ]
