# Generated by Django 5.2 on 2025-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_merge_20250827_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagent',
            name='whitelist_policy',
            field=models.CharField(choices=[('default', 'Default (Owner or Org Members)'), ('manual', 'Allowed Contacts List')], default='default', help_text="Controls who can message this agent and who the agent may contact. Default: user-owned → owner email + verified phone; org-owned → org members' emails + verified phones. Manual: only addresses/numbers listed on the agent's manual allowlist.", max_length=16),
        ),
    ]
