# Generated by Django 5.2 on 2025-08-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_set_all_agents_to_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagent',
            name='whitelist_policy',
            field=models.CharField(choices=[('default', 'Default (Owner or Org Members)'), ('manual', 'Allowed Contacts List')], default='manual', help_text="Controls who can message this agent and who the agent may contact. Manual: only addresses/numbers listed on the agent's allowlist (includes owner/org members by default).", max_length=16),
        ),
    ]
