# Generated by Django 5.2 on 2025-09-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_alter_persistentagent_whitelist_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='commsallowlistentry',
            name='allow_inbound',
            field=models.BooleanField(default=True, help_text='Whether this contact can send messages to the agent'),
        ),
        migrations.AddField(
            model_name='commsallowlistentry',
            name='allow_outbound',
            field=models.BooleanField(default=True, help_text='Whether the agent can send messages to this contact'),
        ),
    ]
