# Generated by Django 5.2 on 2025-09-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_add_inbound_outbound_to_allowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='commsallowlistrequest',
            name='request_inbound',
            field=models.BooleanField(default=True, help_text='Agent is requesting to receive messages from this contact'),
        ),
        migrations.AddField(
            model_name='commsallowlistrequest',
            name='request_outbound',
            field=models.BooleanField(default=True, help_text='Agent is requesting to send messages to this contact'),
        ),
    ]
