# Generated by Django 5.2 on 2025-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_add_direction_to_contact_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentallowlistinvite',
            name='allow_inbound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentallowlistinvite',
            name='allow_outbound',
            field=models.BooleanField(default=True),
        ),
    ]
