# Generated by Django 5.2 on 2025-09-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_add_agent_soft_expiration_switch'),
        ('api', '0109_agentallowlistinvite_allow_inbound_and_more'),
    ]

    operations = [
    ]
