# Generated by Django 5.2 on 2025-09-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_agent_email_idle_toggle'),
        ('api', '0115_persistentagentstep_credits_fields'),
    ]

    operations = [
    ]
