# Generated by Django 5.2 on 2025-09-09 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_merge_20250909_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagent',
            name='last_interaction_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Timestamp of the last user interaction (reply, edit, etc.).', null=True),
        ),
    ]
