# Generated by Django 5.2 on 2025-09-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_backfill_last_interaction_at'),
        ('api', '0118_backfill_set_metered_true'),
    ]

    operations = [
    ]
