# Generated by Django 5.2 on 2025-09-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_create_meteringbatch'),
        ('api', '0122_persistent_endpoint_api_base'),
    ]

    operations = [
    ]
