# Generated by Django 5.2 on 2025-09-16 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_remove_browserllmtier_uniq_browser_tier_order_per_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Internal identifier for referencing this template in code and analytics.', max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('charter', models.TextField(help_text='Pre-built charter the agent will start with.')),
                ('base_schedule', models.CharField(blank=True, help_text="Cron-like schedule expression or interval guideline (e.g., '@daily').", max_length=128)),
                ('schedule_jitter_minutes', models.PositiveIntegerField(default=0, help_text='Maximum minutes of jitter to apply to the base schedule when instancing.')),
                ('event_triggers', models.JSONField(blank=True, default=list, help_text='List of event trigger definitions (webhook names, keywords, etc.).')),
                ('default_tools', models.JSONField(blank=True, default=list, help_text='MCP tool identifiers to enable automatically when hired.')),
                ('recommended_contact_channel', models.CharField(blank=True, help_text="Default contact preference (e.g., 'email', 'sms').", max_length=16)),
                ('category', models.CharField(blank=True, help_text="Grouping label used for UI filtering (e.g., 'Research', 'Operations').", max_length=64)),
                ('hero_image_path', models.CharField(blank=True, help_text='Optional static asset path used for UI illustration.', max_length=255)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first in the directory UI.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'display_name'],
            },
        ),
    ]
