# Generated by Django 5.2 on 2025-09-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_remove_browserllmtier_uniq_browser_tier_order_per_policy_and_more'),
        ('api', '0130_persistentagent_sent_expiration_email'),
    ]

    operations = [
    ]
