# Generated by Django 5.2 on 2025-09-17 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_tool_friendly_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolfriendlyname',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
