# Generated by Django 5.2 on 2025-09-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_merge_20250916_2204'),
        ('api', '0133_alter_toolfriendlyname_id'),
    ]

    operations = [
    ]
