# Generated by Django 5.2 on 2025-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_backfill_organizationbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbilling',
            name='max_extra_tasks',
            field=models.IntegerField(default=0, help_text='Maximum number of additional tasks the org can buy beyond included credits. 0 means disabled; -1 is unlimited.'),
        ),
        migrations.AddField(
            model_name='organizationbilling',
            name='purchased_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of seats purchased for this organization (must cover active members + pending invites beyond the founder).'),
        ),
        migrations.AlterField(
            model_name='organizationbilling',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('org_team', 'Team')], default='free', help_text="The organization's subscription plan", max_length=32),
        ),
        migrations.AlterField(
            model_name='taskcredit',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('startup', 'Startup'), ('org_team', 'Team')], default='free', help_text='The plan under which these credits were granted', max_length=32),
        ),
        migrations.AlterField(
            model_name='userbilling',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('startup', 'Startup')], default='free', help_text="The user's subscription plan", max_length=32),
        ),
    ]
