# Generated by Django 5.2 on 2025-09-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_add_trello_tool_friendly_names'),
        ('api', '0138_meteringbatch_organization_alter_meteringbatch_user_and_more'),
    ]

    operations = [
    ]
