# Generated by Django 5.2 on 2025-09-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_remove_db_stripe_secret_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbilling',
            name='pending_seat_effective_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the pending seat quantity is expected to take effect.', null=True),
        ),
        migrations.AddField(
            model_name='organizationbilling',
            name='pending_seat_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Seat quantity scheduled to take effect in a future billing period.', null=True),
        ),
        migrations.AddField(
            model_name='organizationbilling',
            name='pending_seat_schedule_id',
            field=models.CharField(blank=True, default='', help_text='Stripe subscription schedule ID managing the pending seat change.', max_length=255),
        ),
    ]
