# Generated by Django 5.2 on 2025-09-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_organizationbilling_pending_seat_effective_at_and_more'),
        ('api', '0143_taskcreditconfig_toolcreditcost'),
    ]

    operations = [
    ]
