# Generated by Django 5.2 on 2025-09-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_merge_20250929_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentallowlistinvite',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='commsallowlistentry',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='commsallowlistrequest',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagentcommsendpoint',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='persistentagentconversation',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack'), ('discord', 'Discord'), ('web', 'Web Chat'), ('other', 'Other')], max_length=32),
        ),
    ]
