# Generated by Django 5.2 on 2025-09-26 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_remove_apikey_unique_api_key_user_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagenttask',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Owning organization, when applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browser_use_tasks', to='api.organization'),
        ),
        migrations.AddIndex(
            model_name='browseruseagenttask',
            index=models.Index(fields=['organization', 'created_at'], name='task_org_created_idx'),
        ),
    ]
