# Generated by Django 5.2 on 2025-09-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_merge_20250929_1239'),
        ('api', '0145_browseruseagenttask_organization_and_more'),
    ]

    operations = [
    ]
