# Generated by Django 5.2 on 2025-09-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_alter_agentallowlistinvite_channel_and_more'),
        ('api', '0146_merge_20250929_1905'),
    ]

    operations = [
    ]
