# Generated by Django 5.2 on 2025-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_merge_20250930_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagenttemplate',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Whether to feature this template on the home page.'),
        ),
    ]
