# Generated by Django 5.2 on 2025-10-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_agentcommpeerstate_agentpeerlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='short_description',
            field=models.CharField(blank=True, help_text='Generated short summary of the agent charter for listings.', max_length=280),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='short_description_charter_hash',
            field=models.CharField(blank=True, help_text='SHA256 of the charter used to generate short_description.', max_length=64),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='short_description_requested_hash',
            field=models.CharField(blank=True, help_text='SHA256 of the charter currently pending short description generation.', max_length=64),
        ),
        migrations.AlterField(
            model_name='persistentagentsystemstep',
            name='code',
            field=models.CharField(choices=[('PROCESS_EVENTS', 'Process Events'), ('PEER_LINK_CREATED', 'Peer Link Created'), ('SNAPSHOT', 'Snapshot'), ('CREDENTIALS_PROVIDED', 'Credentials Provided'), ('CONTACTS_APPROVED', 'Contacts Approved')], max_length=64),
        ),
    ]
