# Generated by Django 5.2 on 2025-10-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_add_agent_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsermodelendpoint',
            name='supports_vision',
            field=models.BooleanField(default=False, help_text='Indicates the model can process image or multimodal inputs'),
        ),
        migrations.AddField(
            model_name='persistentmodelendpoint',
            name='supports_vision',
            field=models.BooleanField(default=False, help_text='Indicates the model can process image or multimodal inputs'),
        ),
        migrations.AlterField(
            model_name='persistentagentsystemstep',
            name='code',
            field=models.CharField(choices=[('PROCESS_EVENTS', 'Process Events'), ('PEER_LINK_CREATED', 'Peer Link Created'), ('SNAPSHOT', 'Snapshot'), ('CREDENTIALS_PROVIDED', 'Credentials Provided'), ('CONTACTS_APPROVED', 'Contacts Approved'), ('LLM_CONFIGURATION_REQUIRED', 'LLM Configuration Required')], max_length=64),
        ),
    ]
