# Generated by Django 5.2 on 2025-10-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_agenttransferinvite'),
        ('api', '0155_persistentagent_daily_credit_limit_and_more'),
    ]

    operations = [
    ]
