# Generated by Django 5.2 on 2025-10-14 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_merge_20251009_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source_first', models.CharField(blank=True, max_length=256)),
                ('utm_medium_first', models.CharField(blank=True, max_length=256)),
                ('utm_campaign_first', models.CharField(blank=True, max_length=256)),
                ('utm_content_first', models.CharField(blank=True, max_length=256)),
                ('utm_term_first', models.CharField(blank=True, max_length=256)),
                ('utm_source_last', models.CharField(blank=True, max_length=256)),
                ('utm_medium_last', models.CharField(blank=True, max_length=256)),
                ('utm_campaign_last', models.CharField(blank=True, max_length=256)),
                ('utm_content_last', models.CharField(blank=True, max_length=256)),
                ('utm_term_last', models.CharField(blank=True, max_length=256)),
                ('landing_code_first', models.CharField(blank=True, max_length=128)),
                ('landing_code_last', models.CharField(blank=True, max_length=128)),
                ('fbclid', models.CharField(blank=True, max_length=256)),
                ('fbc', models.CharField(blank=True, max_length=256)),
                ('gclid_first', models.CharField(blank=True, max_length=256)),
                ('gclid_last', models.CharField(blank=True, max_length=256)),
                ('gbraid_first', models.CharField(blank=True, max_length=256)),
                ('gbraid_last', models.CharField(blank=True, max_length=256)),
                ('wbraid_first', models.CharField(blank=True, max_length=256)),
                ('wbraid_last', models.CharField(blank=True, max_length=256)),
                ('msclkid_first', models.CharField(blank=True, max_length=256)),
                ('msclkid_last', models.CharField(blank=True, max_length=256)),
                ('ttclid_first', models.CharField(blank=True, max_length=256)),
                ('ttclid_last', models.CharField(blank=True, max_length=256)),
                ('first_referrer', models.CharField(blank=True, max_length=512)),
                ('last_referrer', models.CharField(blank=True, max_length=512)),
                ('first_landing_path', models.CharField(blank=True, max_length=512)),
                ('last_landing_path', models.CharField(blank=True, max_length=512)),
                ('segment_anonymous_id', models.CharField(blank=True, max_length=256)),
                ('ga_client_id', models.CharField(blank=True, max_length=256)),
                ('first_touch_at', models.DateTimeField(blank=True, null=True)),
                ('last_touch_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Attribution',
                'verbose_name_plural': 'User Attribution',
            },
        ),
    ]
