# Generated by Django 5.2 on 2025-10-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_persistentagentpromptarchive'),
        ('api', '0157_userattribution'),
    ]

    operations = [
    ]
