# Generated by Django 5.2 on 2025-10-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_mark_decodo_proxies_dedicated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='is_dedicated',
            field=models.BooleanField(default=False, help_text='True when this proxy can be allocated as dedicated inventory. Proxies with an active DedicatedProxyAllocation are withheld from the shared pool.'),
        ),
    ]
