# Generated by Django 5.2 on 2025-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_merge_20251014_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagent',
            name='charter',
            field=models.TextField(blank=True),
        ),
    ]
