# Generated by Django 5.2 on 2025-10-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_merge_20251009_1404'),
        ('api', '0158_alter_proxyserver_is_dedicated'),
    ]

    operations = [
    ]
