# Generated by Django 5.2 on 2025-10-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_persistentagentpromptarchive'),
        ('api', '0159_merge_20251010_1920'),
    ]

    operations = [
    ]
