# Generated by Django 5.2 on 2025-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_merge_20251014_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagent',
            name='charter',
            field=models.TextField(blank=True),
        ),
    ]
