# Generated by Django 5.2 on 2025-10-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_alter_persistentagent_charter'),
        ('api', '0161_alter_persistentagent_charter'),
    ]

    operations = [
    ]
