# Generated by Django 5.2 on 2025-10-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_merge_20251015_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsermodelendpoint',
            name='max_output_tokens',
            field=models.PositiveIntegerField(blank=True, help_text="Optional override of the provider's max output tokens; null disables the override.", null=True),
        ),
    ]
