# Generated by Django 5.2 on 2025-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_persistentagentwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagenttask',
            name='webhook_last_called_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent webhook attempt.', null=True),
        ),
        migrations.AddField(
            model_name='browseruseagenttask',
            name='webhook_last_error',
            field=models.TextField(blank=True, help_text='Error message captured from the most recent webhook attempt, if any.', null=True),
        ),
        migrations.AddField(
            model_name='browseruseagenttask',
            name='webhook_last_status_code',
            field=models.IntegerField(blank=True, help_text='HTTP status code returned by the most recent webhook attempt.', null=True),
        ),
        migrations.AddField(
            model_name='browseruseagenttask',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Callback URL invoked when the task reaches a terminal state.', max_length=2048, null=True),
        ),
    ]
