# Generated by Codex on 2025-10-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_embeddingsmodelendpoint_embeddingsllmtier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserverconfig',
            name='auth_method',
            field=models.CharField(choices=[('none', 'None'), ('bearer_token', 'Bearer Token'), ('oauth2', 'OAuth 2.0')], default='none', max_length=32),
        ),
    ]
