# Generated by Codex on 2025-10-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_mcp_oauth_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='mini_description',
            field=models.CharField(
                blank=True,
                help_text='Generated ultra-short summary of the agent charter for compact displays.',
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='mini_description_charter_hash',
            field=models.CharField(
                blank=True,
                help_text='SHA256 of the charter used to generate mini_description.',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='mini_description_requested_hash',
            field=models.CharField(
                blank=True,
                help_text='SHA256 of the charter currently pending mini description generation.',
                max_length=64,
            ),
        ),
    ]
