# Generated by Django 5.2 on 2025-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_persistentagent_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentllmtier',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks tiers reserved for premium routing.'),
        ),
        migrations.AddField(
            model_name='persistenttierendpoint',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='Matches the premium status of the associated tier.'),
        ),
        migrations.AlterUniqueTogether(
            name='persistentllmtier',
            unique_together={('token_range', 'order', 'is_premium')},
        ),
        migrations.AddField(
            model_name='browserllmtier',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks tiers reserved for premium browser routing.'),
        ),
        migrations.AddField(
            model_name='browsertierendpoint',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='Matches the premium status of the associated browser tier.'),
        ),
        migrations.AlterUniqueTogether(
            name='browserllmtier',
            unique_together={('policy', 'order', 'is_premium')},
        ),
    ]
