# Generated by Django 5.2 on 2025-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_persistentpremiumllmtier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of descriptive tags generated from the charter to aid discovery.'),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='tags_charter_hash',
            field=models.CharField(blank=True, help_text='SHA256 of the charter used to generate tags.', max_length=64),
        ),
        migrations.AddField(
            model_name='persistentagent',
            name='tags_requested_hash',
            field=models.CharField(blank=True, help_text='SHA256 of the charter currently pending tag generation.', max_length=64),
        ),
    ]
