# Generated by Django 5.2 on 2025-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_alter_taskcredit_plan_alter_userbilling_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcredit',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('startup', 'Startup'), ('pln_l_m_v1', 'Scale'), ('org_team', 'Team')], default='free', help_text='The plan under which these credits were granted', max_length=32),
        ),
        migrations.AlterField(
            model_name='userbilling',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('startup', 'Startup'), ('pln_l_m_v1', 'Scale')], default='free', help_text="The user's subscription plan", max_length=32),
        ),
    ]
