# Generated by Django 5.2 on 2025-11-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_agent_colors'),
        ('api', '0177_alter_taskcredit_plan_alter_userbilling_subscription'),
    ]

    operations = [
    ]
