# Generated by Django 5.2 on 2025-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_merge_20251104_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattribution',
            name='fbc',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='userattribution',
            name='fbclid',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
