# Generated by Django 5.2 on 2025-11-13 14:52

from django.db import migrations


# Note: This intentionally leaves the token, model, etc fields in the database for legacy information that
# we do not want to lose for statistical reasons. We may fully remove later, but for now, this is to appease
# Django

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_persistentagentsystemmessage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='persistentagentstep',
                    name='cached_tokens',
                ),
                migrations.RemoveField(
                    model_name='persistentagentstep',
                    name='completion_tokens',
                ),
                migrations.RemoveField(
                    model_name='persistentagentstep',
                    name='llm_model',
                ),
                migrations.RemoveField(
                    model_name='persistentagentstep',
                    name='llm_provider',
                ),
                migrations.RemoveField(
                    model_name='persistentagentstep',
                    name='prompt_tokens',
                ),
                migrations.RemoveField(
                    model_name='persistentagentstep',
                    name='total_tokens',
                ),
            ]
        )
    ]
