# Generated by Django 5.2 on 2025-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_remove_persistentagentstep_cached_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribution',
            name='last_client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Most recent client IP observed for this user.', null=True),
        ),
    ]
