# Generated by Django 5.2 on 2025-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_remove_persistentagentstep_cached_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='input_cost_cached',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='USD cost for cached prompt tokens.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='input_cost_total',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Total USD cost for prompt tokens (cached + uncached).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='input_cost_uncached',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='USD cost for uncached prompt tokens.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='output_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='USD cost for completion tokens.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Total USD cost (input + output).', max_digits=12, null=True),
        ),
    ]
