# Generated by Django 5.2 on 2025-11-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_persistentagentcompletion_cost_fields'),
        ('api', '0185_userattribution_last_client_ip'),
    ]

    operations = [
    ]
