# Generated by Django 5.2 on 2025-11-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_browseruseagenttask_cost_fields'),
        ('api', '0188_llmprovider_model_prefix_and_more'),
    ]

    operations = [
    ]
