# Generated by Django 5.2 on 2025-11-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_add_max_llm_tier'),
        ('api', '0191_persistentagent_proactive_sched_idx'),
    ]

    operations = [
    ]
