# Generated by Django 5.2 on 2025-11-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_evalrun_evalruntask'),
        ('api', '0192_merge_20251119_1544'),
    ]

    operations = [
    ]
