# Generated by Django 5.2 on 2025-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_merge_20251119_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbilling',
            name='max_contacts_per_agent',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="If set, overrides the plan's max contacts per agent for this user. Leave blank to use the default from the subscription plan.", null=True),
        ),
    ]
