# Generated by Django 5.2 on 2025-11-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_promptconfig_enabled_tool_limits'),
        ('api', '0194_userbilling_max_contacts_per_agent'),
    ]

    operations = [
    ]
