# Generated by Django 5.2 on 2025-11-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_clear_openrouter_persistent_api_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentmodelendpoint',
            name='supports_temperature',
            field=models.BooleanField(default=True, help_text='Indicates whether this model accepts a temperature parameter'),
        ),
    ]
