# Generated by Django 5.2 on 2025-11-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_add_supports_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsermodelendpoint',
            name='supports_temperature',
            field=models.BooleanField(default=True, help_text='Indicates whether this model accepts a temperature parameter'),
        ),
    ]
