# Generated by Django 5.2 on 2025-11-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_merge_20251119_1953'),
        ('api', '0198_add_browser_supports_temperature'),
    ]

    operations = [
    ]
