# Generated by Django 5.2 on 2025-11-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_persistentagent_preferred_llm_tier_and_more'),
        ('api', '0199_merge_20251120_1338'),
    ]

    operations = [
    ]
