# Generated by Django 5.2 on 2025-11-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_evalsuiterun_evalrun_suite_run'),
        ('api', '0200_merge_20251120_1526'),
    ]

    operations = [
    ]
