# Generated by Django 5.2 on 2025-11-25 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_eval_run_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptconfig',
            name='max_unified_history_hysteresis',
            field=models.PositiveIntegerField(default=20, help_text='Unified history hysteresis for max tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='promptconfig',
            name='max_unified_history_limit',
            field=models.PositiveIntegerField(default=120, help_text='Unified history event limit for max tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='promptconfig',
            name='premium_unified_history_hysteresis',
            field=models.PositiveIntegerField(default=20, help_text='Unified history hysteresis for premium tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='promptconfig',
            name='premium_unified_history_limit',
            field=models.PositiveIntegerField(default=120, help_text='Unified history event limit for premium tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='promptconfig',
            name='standard_unified_history_hysteresis',
            field=models.PositiveIntegerField(default=20, help_text='Unified history hysteresis for standard tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='promptconfig',
            name='standard_unified_history_limit',
            field=models.PositiveIntegerField(default=120, help_text='Unified history event limit for standard tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
