# Generated by Django 5.2 on 2025-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_promptconfig_max_unified_history_hysteresis_and_more'),
        ('api', '0204_eval_cost_attribution'),
    ]

    operations = [
    ]
