# Generated by Django 5.2 on 2025-12-01 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_alter_persistentagentsystemstep_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentAgentEmailFooter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Label to identify this footer in admin.', max_length=128)),
                ('html_content', models.TextField(help_text='HTML snippet appended to the email template.')),
                ('text_content', models.TextField(help_text='Plaintext snippet appended to the email body.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persistent Agent Email Footer',
                'verbose_name_plural': 'Persistent Agent Email Footers',
                'ordering': ['name'],
            },
        ),
    ]
