# Generated by Django 5.2 on 2025-12-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_persistentagentemailfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentmodelendpoint',
            name='reasoning_effort',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=None, help_text='Default reasoning effort to pass when reasoning is supported', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='persistentmodelendpoint',
            name='supports_reasoning',
            field=models.BooleanField(default=False, help_text='Indicates the model accepts reasoning parameters'),
        ),
    ]
