# Generated by Django 5.2 on 2025-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0218_persistentmodelendpoint_reasoning_effort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagentcompletion',
            name='thinking_content',
            field=models.TextField(blank=True, help_text='Reasoning/thinking content returned by the LLM when available.', null=True),
        ),
    ]
