# Generated by Django 5.2 on 2025-12-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_persistentagentcompletion_thinking_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistenttierendpoint',
            name='reasoning_effort_override',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=None, help_text='Optional reasoning effort override applied when the endpoint supports reasoning.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profilepersistenttierendpoint',
            name='reasoning_effort_override',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=None, help_text='Optional reasoning effort override applied when the endpoint supports reasoning.', max_length=16, null=True),
        ),
    ]
