# Generated by Django 5.2 on 2025-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_browser_extraction_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseruseagenttask',
            name='requires_vision',
            field=models.BooleanField(default=False, help_text='When true, restricts browser tasks to vision-capable LLM endpoints only.'),
        ),
    ]
