# Generated by Django 5.2 on 2025-12-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_addon_entitlement'),
        ('api', '0222_browseruseagenttask_requires_vision'),
    ]

    operations = [
    ]
