# Generated by Django 5.2 on 2025-12-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_toolratelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagentsystemstep',
            name='code',
            field=models.CharField(choices=[('PROCESS_EVENTS', 'Process Events'), ('PEER_LINK_CREATED', 'Peer Link Created'), ('SNAPSHOT', 'Snapshot'), ('CREDENTIALS_PROVIDED', 'Credentials Provided'), ('CONTACTS_APPROVED', 'Contacts Approved'), ('LLM_CONFIGURATION_REQUIRED', 'LLM Configuration Required'), ('PROACTIVE_TRIGGER', 'Proactive Trigger'), ('SYSTEM_DIRECTIVE', 'System Directive'), ('BURN_RATE_COOLDOWN', 'Burn Rate Cooldown'), ('RATE_LIMIT', 'Rate Limit')], max_length=64),
        ),
        migrations.AlterField(
            model_name='toolratelimit',
            name='plan',
            field=models.ForeignKey(help_text='Tool configuration the rate limit applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='api.toolconfig'),
        ),
    ]
