# Generated by Django 5.2 on 2025-12-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0224_alter_persistentagentsystemstep_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='persistentagentstep',
            name='pa_step_agent_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='persistentagenttoolcall',
            name='pa_tool_step_idx',
        ),
        migrations.AddIndex(
            model_name='persistentagentstep',
            index=models.Index(fields=['agent', 'created_at', 'id'], name='pa_step_agent_ts_idx'),
        ),
    ]
