# Generated by Django 5.2 on 2025-12-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_add_user_flags'),
        ('api', '0227_daily_credit_per_plan'),
    ]

    operations = [
    ]
