# Generated by Django 5.2 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0228_merge_0227_add_user_flags_0227_daily_credit_per_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="browserconfig",
            name="vision_detail_level",
            field=models.CharField(
                choices=[("auto", "Auto"), ("low", "Low"), ("high", "High")],
                default="auto",
                help_text="Vision detail level to pass to browser_use when vision support is enabled.",
                max_length=8,
            ),
        ),
    ]
