# Generated by Django 5.2 on 2025-12-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_merge_20251208_1812'),
        ('api', '0228_merge_0227_add_user_flags_0227_daily_credit_per_plan'),
    ]

    operations = [
    ]
