# Generated by Django 5.2 on 2025-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_add_agent_cron_throttle_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentagentmessage',
            name='latest_error_message',
            field=models.TextField(blank=True),
        ),
    ]
