# Generated by Django 5.2 on 2025-12-15 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_add_agent_cron_throttle_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolconfig',
            name='duplicate_similarity_threshold',
            field=models.FloatField(default=0.97, help_text='Similarity ratio required before blocking a potential duplicate outbound message.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
