# Generated by Django 5.2 on 2025-12-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_alter_persistentagentmessage_latest_error_message'),
        ('api', '0231_toolconfig_duplicate_similarity_threshold'),
    ]

    operations = [
    ]
