# Generated by Django 5.2 on 2025-12-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_merge_20251212_1550'),
        ('api', '0232_merge_20251215_2135'),
    ]

    operations = [
    ]
