# Generated by Django 5.2 on 2025-12-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0233_comms_endpoint_ci_unique'),
        ('api', '0233_merge_20251216_1623'),
    ]

    operations = [
    ]
