# Generated by Django 5.2 on 2025-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_merge_20251217_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcredit',
            name='grant_type',
            field=models.CharField(choices=[('Plan', 'Plan'), ('Compensation', 'Compensation'), ('Promo', 'Promo'), ('task_pack', 'Task Pack')], default='Plan', help_text='Type of grant for these credits (e.g., PLAN, COMPENSATION, PROMO, TASK_PACK)', max_length=32),
        ),
    ]
