# Generated by Codex on 2025-02-10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0240_file_handler_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentfsnode",
            name="content",
            field=models.FileField(
                blank=True,
                help_text="Binary content for files. Empty for directories.",
                max_length=512,
                null=True,
                upload_to=api.models.agent_fs_upload_to,
            ),
        ),
    ]
