# Generated by Django 5.2 on 2025-12-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_persistentmodelendpoint_openrouter_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentmodelendpoint',
            name='max_input_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum input tokens for this endpoint. Leave blank for automatic (no limit).', null=True),
        ),
    ]
