# Generated by Django 5.2 on 2025-12-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_add_max_input_tokens_to_persistentmodelendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsermodelendpoint',
            name='low_latency',
            field=models.BooleanField(default=False, help_text='Marks this endpoint as low latency/high performance.'),
        ),
        migrations.AddField(
            model_name='embeddingsmodelendpoint',
            name='low_latency',
            field=models.BooleanField(default=False, help_text='Marks this endpoint as low latency/high performance.'),
        ),
        migrations.AddField(
            model_name='filehandlermodelendpoint',
            name='low_latency',
            field=models.BooleanField(default=False, help_text='Marks this endpoint as low latency/high performance.'),
        ),
        migrations.AddField(
            model_name='persistentmodelendpoint',
            name='low_latency',
            field=models.BooleanField(default=False, help_text='Marks this endpoint as low latency/high performance.'),
        ),
    ]
