# Generated by Django 5.2 on 2026-01-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_add_low_latency_to_endpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentallowlistinvite',
            name='can_configure',
            field=models.BooleanField(default=False, help_text='Whether this contact can instruct the agent to update its charter or schedule'),
        ),
        migrations.AddField(
            model_name='commsallowlistentry',
            name='can_configure',
            field=models.BooleanField(default=False, help_text='Whether this contact can instruct the agent to update its charter or schedule'),
        ),
        migrations.AddField(
            model_name='commsallowlistrequest',
            name='request_configure',
            field=models.BooleanField(default=False, help_text='Whether to grant this contact authority to update agent charter/schedule'),
        ),
    ]
