# Generated by Django 5.2 on 2026-01-06 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_persistentagent_kanban_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptconfig',
            name='premium_tool_call_history_limit',
            field=models.PositiveSmallIntegerField(default=50, help_text='Number of recent tool calls included for premium tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='promptconfig',
            name='standard_tool_call_history_limit',
            field=models.PositiveSmallIntegerField(default=40, help_text='Number of recent tool calls included for standard tier agents.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
