# Generated by Django 5.2 on 2026-01-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_email_oauth_models'),
        ('api', '0251_toolratelimit_plan_fk'),
    ]

    operations = [
    ]
