# Generated by Django 5.2 on 2026-01-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0258_add_kanban_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyserver',
            name='auto_deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When this proxy was automatically deactivated due to failures', null=True),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='consecutive_health_failures',
            field=models.PositiveIntegerField(default=0, help_text='Count of consecutive health check failures'),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='deactivation_reason',
            field=models.CharField(blank=True, default='', help_text="Reason for deactivation (e.g., 'repeated_health_check_failures')", max_length=64),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='last_health_check_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent health check', null=True),
        ),
    ]
