# Generated by Django 5.2 on 2026-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0263_alter_persistentagentcompletion_completion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='daily_credit_hard_limit_notice_at',
            field=models.DateTimeField(blank=True, help_text='Last time the owner was notified that the daily hard limit was reached.', null=True),
        ),
    ]
