# Generated by Django 5.2 on 2026-01-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0262_agentcollaborator_agentcollaboratorinvite'),
        ('api', '0263_alter_persistentagentcompletion_completion_type'),
    ]

    operations = [
    ]
