# Generated by Django 5.2 on 2026-01-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0264_merge_20260120_1532'),
        ('api', '0264_persistentagent_daily_credit_hard_limit_notice_at'),
    ]

    operations = [
    ]
