# Generated by Django 5.2 on 2026-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0265_merge_20260120_1851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persistentagentsystemstep",
            name="code",
            field=models.CharField(
                choices=[
                    ("PROCESS_EVENTS", "Process Events"),
                    ("PEER_LINK_CREATED", "Peer Link Created"),
                    ("SNAPSHOT", "Snapshot"),
                    ("CREDENTIALS_PROVIDED", "Credentials Provided"),
                    ("CONTACTS_APPROVED", "Contacts Approved"),
                    ("COLLABORATOR_ADDED", "Collaborator Added"),
                    ("LLM_CONFIGURATION_REQUIRED", "LLM Configuration Required"),
                    ("PROACTIVE_TRIGGER", "Proactive Trigger"),
                    ("SYSTEM_DIRECTIVE", "System Directive"),
                    ("BURN_RATE_COOLDOWN", "Burn Rate Cooldown"),
                    ("RATE_LIMIT", "Rate Limit"),
                ],
                max_length=64,
            ),
        ),
    ]
