# Generated by Django 5.2 on 2026-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_add_collaborator_added_system_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribution',
            name='fbp',
            field=models.CharField(blank=True, default='', help_text='Meta Browser ID (_fbp cookie value).', max_length=256),
        ),
        migrations.AddField(
            model_name='userattribution',
            name='last_user_agent',
            field=models.TextField(blank=True, default='', help_text='Most recent user agent observed for this user.'),
        ),
    ]
