# Generated by Django 5.2 on 2026-01-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0268_referral_system_scaffolding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribution',
            name='referral_credit_granted_at',
            field=models.DateTimeField(blank=True, help_text='When referral credits were granted to the referrer (null if pending or N/A)', null=True),
        ),
    ]
