# Generated by Django 5.2 on 2026-01-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0269_referral_deferred_grant_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattribution',
            name='referrer_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Referral code used at signup (direct referral from another user)', max_length=32),
        ),
    ]
