# Generated by Django 5.2 on 2026-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0276_burn_rate_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagenttoolcall',
            name='execution_duration_ms',
            field=models.IntegerField(blank=True, help_text='Elapsed time in milliseconds for executing the tool call.', null=True),
        ),
    ]
