# Generated by Django 5.2 on 2026-01-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0276_burn_rate_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('solutions_partner', 'Solutions Partner'), ('billing_admin', 'Billing'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('solutions_partner', 'Solutions Partner'), ('billing_admin', 'Billing'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
