# Generated by Django 5.2 on 2026-02-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_add_tool_call_duration_ms'),
        ('api', '0277_system_setting'),
    ]

    operations = [
    ]
