# Generated by Django 6.0 on 2026-02-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0286_intelligencetier_is_default'),
        ('api', '0287_add_personal_free_trial_enforcement_switch'),
    ]

    operations = [
    ]
