# Generated by Django 5.2 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0295_add_fish_collateral_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="userattribution",
            name="rdt_cid_first",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="userattribution",
            name="rdt_cid_last",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
