# Generated by Django 5.2 on 2026-02-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0296_userattribution_reddit_click_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persistentagentcompletion",
            name="completion_type",
            field=models.CharField(
                choices=[
                    ("orchestrator", "Orchestrator"),
                    ("compaction", "Comms Compaction"),
                    ("step_compaction", "Step Compaction"),
                    ("tag", "Tag Generation"),
                    ("short_description", "Short Description"),
                    ("mini_description", "Mini Description"),
                    ("avatar_visual_description", "Avatar Visual Description"),
                    ("image_generation", "Image Generation"),
                    ("tool_search", "Tool Search"),
                    ("template_clone", "Template Clone"),
                    ("other", "Other"),
                ],
                default="orchestrator",
                help_text="Origin of the completion (orchestrator loop, compaction, tag generation, etc.).",
                max_length=64,
            ),
        ),
    ]
