# Generated by Django 6.0 on 2026-02-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0294_taskcredit_free_trial_start_flag'),
        ('api', '0296_userattribution_reddit_click_ids'),
    ]

    operations = [
    ]
