# Generated by Django 6.0 on 2026-03-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0297_alter_persistentagentcompletion_completion_type'),
        ('api', '0297_merge_20260226_2140'),
    ]

    operations = [
    ]
