# Generated by Django 6.0 on 2026-02-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0297_alter_persistentagentcompletion_completion_type'),
        ('api', '0298_add_pricing_modal_almost_full_screen_flag'),
    ]

    operations = [
    ]
