# Generated by Django 6.0 on 2026-03-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0299_merge_20260227_2004'),
        ('api', '0303_add_support_intercom_flag'),
    ]

    operations = [
    ]
