# Generated by Django 6.0 on 2026-03-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0304_add_agent_retry_completion_on_web_session_activation_switch'),
        ('api', '0304_merge_20260305_1844'),
    ]

    operations = [
    ]
