# Generated by Django 6.0 on 2026-03-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0305_merge_20260305_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentagent',
            name='avatar_last_generation_attempt_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent avatar image generation attempt.', null=True),
        ),
        migrations.AlterField(
            model_name='persistentagentcompletion',
            name='completion_type',
            field=models.CharField(choices=[('orchestrator', 'Orchestrator'), ('compaction', 'Comms Compaction'), ('step_compaction', 'Step Compaction'), ('tag', 'Tag Generation'), ('short_description', 'Short Description'), ('mini_description', 'Mini Description'), ('avatar_visual_description', 'Avatar Visual Description'), ('avatar_image_generation', 'Avatar Image Generation'), ('image_generation', 'Image Generation'), ('tool_search', 'Tool Search'), ('template_clone', 'Template Clone'), ('other', 'Other')], default='orchestrator', help_text='Origin of the completion (orchestrator loop, compaction, tag generation, etc.).', max_length=64),
        ),
    ]
