# Generated by Django 6.0 on 2026-03-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0307_dailycreditconfig_offpeak_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmroutingprofile',
            name='summarization_endpoint',
            field=models.ForeignKey(blank=True, help_text='Optional endpoint override used for summarization and lightweight generation tasks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarization_profiles', to='api.persistentmodelendpoint'),
        ),
    ]
