# Generated by Django 6.0 on 2026-03-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0307_dailycreditconfig_offpeak_threshold'),
        ('api', '0307_userbilling_execution_paused_and_more'),
    ]

    operations = [
    ]
