# Generated by Django 6.0 on 2026-03-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0308_merge_20260309_1921'),
        ('api', '0309_backfill_default_agent_email_aliases'),
    ]

    operations = [
    ]
