# Generated by Django 6.0 on 2026-03-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0310_imagegenerationllmtier_use_case'),
        ('api', '0310_merge_20260309_2020'),
    ]

    operations = [
    ]
