# Generated by Codex on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0311_merge_20260310_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationbilling",
            name="execution_pause_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("billing_delinquency", "Billing delinquency"),
                    ("trial_conversion_failed", "Trial conversion failed"),
                    ("admin_manual_pause", "Admin manual pause"),
                ],
                default="",
                help_text="Machine-readable reason for the current execution pause.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="userbilling",
            name="execution_pause_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("billing_delinquency", "Billing delinquency"),
                    ("trial_conversion_failed", "Trial conversion failed"),
                    ("admin_manual_pause", "Admin manual pause"),
                ],
                default="",
                help_text="Machine-readable reason for the current execution pause.",
                max_length=64,
            ),
        ),
    ]
