# Generated by Django 6.0 on 2026-03-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0314_add_cta_pricing_cancel_text_under_btn_flag'),
        ('api', '0314_pipedreamappselection'),
    ]

    operations = [
    ]
