# Generated by Django 6.0 on 2026-03-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0315_add_cta_start_free_trial_flag'),
        ('api', '0315_merge_20260311_2022'),
        ('api', '0317_add_simplified_chat_ui_flag'),
    ]

    operations = [
    ]
