# Generated by Django 6.0 on 2026-03-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0322_persistentagentcustomtool'),
        ('api', '0324_add_user_trial_eligibility_enforcement_flag'),
    ]

    operations = [
    ]
