# Generated by Django 6.0 on 2026-03-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0324_add_cta_no_charge_during_trial_flag'),
        ('api', '0327_persistentagentinboundwebhook'),
    ]

    operations = [
    ]
