# Generated by Django 6.0 on 2026-03-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0327_usertrialactivation'),
        ('api', '0328_merge_20260325_1848'),
    ]

    operations = [
    ]
