# Generated by Django 5.2 on 2025-07-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_create_landingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the landing page, auto-generated if not provided.', max_length=128, unique=True),
        ),
    ]
