# Generated by Django 5.2 on 2025-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_landingpage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text',
            field=models.CharField(blank=True, help_text='Text displayed prominently on the landing page. Use {blue} and {/blue} to format text in blue.', max_length=256),
        ),
    ]
