# Generated by Django 5.2 on 2025-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_landingpage_hero_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='private_description',
            field=models.TextField(blank=True, help_text='Internal-only notes for this landing page.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='utm_content',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='utm_source',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='utm_term',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
