# Generated by Django 5.2 on 2026-02-05 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_landingpage_private_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniModeCampaignPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text="Case-insensitive pattern for utm_campaign. Use '*' as a wildcard (examples: agents_202602, c-*, bigcampaign).", max_length=256, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, help_text='Optional internal notes about when to use this pattern.', max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mini mode campaign pattern',
                'verbose_name_plural': 'Mini mode campaign patterns',
                'ordering': ('pattern',),
            },
        ),
    ]
